import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { css } from '~/client/styled-system/css';
import { ApolloWrapper } from '~/services/apolloForSSR';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2
          className={css({
            bgColor: 'blue',
            p: 4,
            textAlign: 'center',
          })}
        >
          header
        </h2>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
