'use client';
import { ApolloClient, ApolloProvider, NormalizedCacheObject } from '@apollo/client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cache } from '~/client/services/apolloCache';
import { typeDefs } from '~/server/schema';

const client: ApolloClient<NormalizedCacheObject> = new ApolloClient({
  cache,
  uri: 'http://0.0.0.0:3000/graphql',
  headers: {
    // authorization: localStorage.getItem('token') || '',
    authorization: '',
  },
  typeDefs,
  resolvers: {},
});

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
